#type: args

train:
  epochs: 1000
  batch_size: 8
  lr: 1.0e-3

diffusion:
  layers: 6
  channels: 64
  nheads: 16
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  eval_length: 32

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
  use_guide: false
